version: "3.9"

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  flask:
    build:
      context: ./backend
      dockerfile: .docker/backend/Dockerfile
    restart: always
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/my-database
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  nextjs:
    build:
      context: ./frontend
      dockerfile: .docker/frontend/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
